---
- include_vars: users.yml

- name: Download newrelic zip file in apps directory
  get_url:
    url: https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip
    dest: '/home/{{item.user_name}}/apps'
    mode: '0754'
    owner: '{{item.user_name}}'
  when: '{{ item.use_sudo}} == False'
  with_items: '{{users}}'
